#!/bin/sh

if [ $# -eq 0 ]; then
	echo "No Arguments supplied"
	echo "off - To Switch off the projector"
	echo "on  - To Switch on the Projector"
elif [ $1 = "off" ]; then
      sudo echo "off" > /sys/devices/platform/lirc_rpi/receive
      sudo echo "off" > /sys/devices/platform/lirc_rpi/receive
elif [ $1 = "on" ]; then
      sudo echo "off" > /sys/devices/platform/lirc_rpi/receive

fi
